var test = require('tape');
var ErrorWithCause = require('error-cause/Error');

var inspect = require('../');

test('type error', function (t) {
    t.plan(1);
    var aerr = new TypeError();
    aerr.bar = 555;
    aerr.bar = [1, 2, 3];

    var berr = new TypeError('tuv');
    berr.baz = 555;

    var cerr = new SyntaxError();
    cerr.message = 'whoa';
    cerr['a-b'] = 5;

    var withCause = new ErrorWithCause('bar', { cause: 'bar' });
    var withCausePlus = new ErrorWithCause('bar', { cause: 'bar' });
    withCausePlus.bar = 'bar';
    var withUndefinedCause = new ErrorWithCause('bar', { cause: undefined });
    var withEnumerableCause = new Error('bar');
    withEnumerableCause.cause = 'bar';

    var obj = [
        new TypeError(),
        new TypeError('xxx'),
        aerr,
        berr,
        cerr,
        withCause,
        withCausePlus,
        withUndefinedCause,
        withEnumerableCause
    ];
    t.equal(inspect(obj), '[ ' + [
        '[TypeError]',
        '[TypeError: xxx]',
        '{ [TypeError] bar: 555, bar: [ 1, 2, 3 ] }',
        '{ [TypeError: tuv] baz: 555 }',
        '{ [SyntaxError: whoa] message: \'whoa\', \'a-b\': 5 }',
        'cause' in Error.prototype ? '[Error: bar]' : '{ [Error: bar] [cause]: \'bar\' }',
        '{ [Error: bar] ' + ('cause' in Error.prototype ? '' : '[cause]: \'bar\', ') + 'bar: \'bar\' }',
        'cause' in Error.prototype ? '[Error: bar]' : '{ [Error: bar] [cause]: undefined }',
        '{ [Error: bar] cause: \'bar\' }'
    ].join(', ') + ' ]');
});
